### ISSUE TITLE
Failing to npm install on raspberry pi

### ISSUE THREAD

**Issue by EdwardLeahy** [molefrog/cupsidity#3]
Hi, I'm trying to install cupsidity on a raspberry pi 2 model B. I have node (version 0.12.0) and npm (version 2.5.1) installed.

When I run `npm install cupsidity`, I get the following error:

```
> cupsidity@0.0.2 install /home/pi/qrpi/node_modules/cupsidity
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/pi/qrpi/node_modules/cupsidity/build'
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:11:30: error: ‘Arguments’ does not name a type
../src/binding.cc:11:41: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/binding.cc:12:32: error: ‘Arguments’ does not name a type
../src/binding.cc:12:43: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/binding.cc:18:29: error: ‘Arguments’ does not name a type
../src/binding.cc:18:40: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/binding.cc:19:31: error: ‘Arguments’ does not name a type
../src/binding.cc:19:42: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/binding.cc:25:31: error: ‘Arguments’ does not name a type
../src/binding.cc:25:42: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/binding.cc: In function ‘void RegisterModule(v8::Handle<v8::Object>)’:
../src/binding.cc:29:48: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [9], v8::Handle<v8::Value> (&)(const int&))’
../src/binding.cc:29:48: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../src/binding.cc:30:52: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [11], v8::Handle<v8::Value> (&)(const int&))’
../src/binding.cc:30:52: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../src/binding.cc:32:47: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [8], v8::Handle<v8::Value> (&)(const int&))’
../src/binding.cc:32:47: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../src/binding.cc:33:50: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))’
../src/binding.cc:33:50: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../src/binding.cc:35:50: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))’
../src/binding.cc:35:50: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
binding.target.mk:84: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/pi/qrpi/node_modules/cupsidity/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.7-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/qrpi/node_modules/cupsidity
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.18.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cupsidity"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! cupsidity@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cupsidity@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cupsidity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cupsidity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/qrpi/npm-debug.log
```

It installs completely fine on my macbook pro, which made me wonder if it was to do with compiling from C++, but I have gcc, g++ and closurecompiler(npm) installed, and it still doesn't work :(. Do you have any idea what would be causing this problem?

Thanks!

**Comment by molefrog** [comment]
@EdwardLeahy I've used it on my Raspberry Pi and it worked fine. Unfortunately, I don't a have a chance to test it right now. Will let you know as soon as possible. At the first glance it seems that I've been working with older version of node.js.

**Comment by molefrog** [comment]
@EdwardLeahy Does it work on your laptop with the same node.js version?

**Comment by EdwardLeahy** [comment]
Yep, the version of node was the problem! I removed node and npm and installed node v0.10.35, and npm v2.1.11, and cupsidity installed completely fine.

Thanks for your help and for this package!

**Comment by arathael** [comment]
Is this going to be compatible with node v0.12 or v4 ?

**Comment by molefrog** [comment]
@arathael Sorry, I stopped using it in my own projects, so haven't been looking at it in a while. I do think though that it should be compatible with newer node version.

In node v0.12 they have changed native bindings interface, but luckily there is an abstraction (see #4) that allows to write code that works well in every version.
